export const ERROR_CODES = {
  // 认证相关错误
  AUTH_TOKEN_MISSING: 'AUTH_001',
  AUTH_TOKEN_INVALID: 'AUTH_002',
  AUTH_TOKEN_EXPIRED: 'AUTH_003',
  AUTH_UNAUTHORIZED: 'AUTH_004',
  AUTH_VERIFICATION_FAILED: 'AUTH_005',

  // Cognito 相关错误
  COGNITO_VERIFICATION_FAILED: 'COGNITO_001',
  COGNITO_CONFIG_MISSING: 'COGNITO_002',
  COGNITO_CONFIG_ERROR: 'COGNITO_003',
  COGNITO_USER_NOT_FOUND: 'COGNITO_004',
  COGNITO_INVALID_PASSWORD: 'COGNITO_005',
  COGNITO_CODE_MISMATCH: 'COGNITO_006',
  COGNITO_CODE_EXPIRED: 'COGNITO_007',
  COGNITO_REGISTRATION_FAILED: 'COGNITO_008',
  COGNITO_LOGIN_FAILED: 'COGNITO_009',
  COGNITO_USER_LIST_FAILED: 'COGNITO_010',
  COGNITO_GROUP_NOT_FOUND: 'COGNITO_011',
  COGNITO_ADD_USER_TO_GROUP_FAILED: 'COGNITO_012',
  COGNITO_GROUP_ALREADY_EXISTS: 'COGNITO_013',
  COGNITO_GROUP_CREATE_FAILED: 'COGNITO_014',
  COGNITO_GROUP_UPDATE_FAILED: 'COGNITO_015',
  COGNITO_GROUP_DELETE_FAILED: 'COGNITO_016',
  COGNITO_GROUP_LIST_FAILED: 'COGNITO_017',
  COGNITO_GROUP_GET_FAILED: 'COGNITO_018',

  // DynamoDB 相关错误
  DYNAMODB_CONNECTION_ERROR: 'DYNAMODB_001',
  DYNAMODB_ITEM_NOT_FOUND: 'DYNAMODB_002',
  DYNAMODB_VALIDATION_ERROR: 'DYNAMODB_003',
  DYNAMODB_CONSTRAINT_VIOLATION: 'DYNAMODB_004',
  DYNAMODB_OPERATION_FAILED: 'DYNAMODB_005',

  // 验证相关错误
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_001',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_002',
  VALIDATION_INVALID_VALUE: 'VALIDATION_003',
  VALIDATION_DATE_FORMAT_INVALID: 'VALIDATION_006',

  // 业务逻辑错误
  BUSINESS_RULE_VIOLATION: 'BUSINESS_001',
  BUSINESS_OPERATION_NOT_ALLOWED: 'BUSINESS_002',
  BUSINESS_RESOURCE_CONFLICT: 'BUSINESS_003',

  // 用户相关业务错误
  USER_REGISTRATION_DISABLED: 'USER_001',

  // 系统错误
  SYSTEM_INTERNAL_ERROR: 'SYSTEM_001',
  SYSTEM_SERVICE_UNAVAILABLE: 'SYSTEM_002',
  SYSTEM_TIMEOUT: 'SYSTEM_003',

  // 网络相关错误
  NETWORK_CONNECTION_ERROR: 'NETWORK_001',
  NETWORK_TIMEOUT: 'NETWORK_002',

  // 资源相关错误
  RESOURCE_NOT_FOUND: 'RESOURCE_001',
  RESOURCE_ACCESS_DENIED: 'RESOURCE_002',

  // S3 相关错误
  S3_UPLOAD_FAILED: 'S3_001',
  S3_DOWNLOAD_FAILED: 'S3_002',
  S3_BUCKET_NOT_FOUND: 'S3_003',
  S3_ACCESS_DENIED: 'S3_004',
  S3_CONFIG_ERROR: 'S3_005',
  S3_DELETE_FAILED: 'S3_006',

  // Vector Database 相关错误
  VECTOR_DB_CONNECTION_ERROR: 'VECTOR_DB_001',
  VECTOR_DB_INDEX_ERROR: 'VECTOR_DB_002',
  VECTOR_DB_QUERY_FAILED: 'VECTOR_DB_003',
  VECTOR_DB_STORE_FAILED: 'VECTOR_DB_004',
  VECTOR_DB_SEARCH_FAILED: 'VECTOR_DB_005',
  VECTOR_DB_DELETE_FAILED: 'VECTOR_DB_006',

  // AI Service 相关错误
  AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_001',
  AI_SERVICE_RATE_LIMIT: 'AI_SERVICE_002',
  AI_SERVICE_INVALID_RESPONSE: 'AI_SERVICE_003',
  AI_SERVICE_EMBEDDING_FAILED: 'AI_SERVICE_004',

  // RAG 相关错误
  RAG_DOCUMENT_PROCESSING_FAILED: 'RAG_001',
  RAG_DOCUMENT_DELETE_FAILED: 'RAG_002',
  RAG_DOCUMENT_SEARCH_FAILED: 'RAG_003',

  // Trade 相关错误
  TRADE_NOT_FOUND: 'TRADE_001',
  TRADE_INVALID_STATUS: 'TRADE_002',
  TRADE_OPERATION_FAILED: 'TRADE_003',
  TRADE_ACCESS_DENIED: 'TRADE_004',

  // Image 相关错误
  IMAGE_UPLOAD_FAILED: 'IMAGE_001',
  IMAGE_FORMAT_INVALID: 'IMAGE_002',
  IMAGE_SIZE_EXCEEDED: 'IMAGE_003',
  IMAGE_DELETE_PERMISSION_DENIED: 'IMAGE_004',
  IMAGE_RATE_LIMITED: 'IMAGE_005',
  IMAGE_LEGACY_DISABLED: 'IMAGE_006',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
