export const ERROR_CODES = {
  // 认证相关错误
  AUTH_TOKEN_MISSING: 'AUTH_001',
  AUTH_TOKEN_INVALID: 'AUTH_002',
  AUTH_TOKEN_EXPIRED: 'AUTH_003',
  AUTH_UNAUTHORIZED: 'AUTH_004',
  
  // Cognito 相关错误
  COGNITO_VERIFICATION_FAILED: 'COGNITO_001',
  COGNITO_CONFIG_MISSING: 'COGNITO_002',
  COGNITO_USER_NOT_FOUND: 'COGNITO_003',
  COGNITO_INVALID_PASSWORD: 'COGNITO_004',
  
  // DynamoDB 相关错误
  DYNAMODB_CONNECTION_ERROR: 'DYNAMODB_001',
  DYNAMODB_ITEM_NOT_FOUND: 'DYNAMODB_002',
  DYNAMODB_VALIDATION_ERROR: 'DYNAMODB_003',
  DYNAMODB_CONSTRAINT_VIOLATION: 'DYNAMODB_004',
  
  // 验证相关错误
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_001',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_002',
  VALIDATION_INVALID_VALUE: 'VALIDATION_003',
  
  // 业务逻辑错误
  BUSINESS_RULE_VIOLATION: 'BUSINESS_001',
  BUSINESS_OPERATION_NOT_ALLOWED: 'BUSINESS_002',
  BUSINESS_RESOURCE_CONFLICT: 'BUSINESS_003',
  
  // 系统错误
  SYSTEM_INTERNAL_ERROR: 'SYSTEM_001',
  SYSTEM_SERVICE_UNAVAILABLE: 'SYSTEM_002',
  SYSTEM_TIMEOUT: 'SYSTEM_003',
  
  // 网络相关错误
  NETWORK_CONNECTION_ERROR: 'NETWORK_001',
  NETWORK_TIMEOUT: 'NETWORK_002',
  
  // 资源相关错误
  RESOURCE_NOT_FOUND: 'RESOURCE_001',
  RESOURCE_ACCESS_DENIED: 'RESOURCE_002',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];